# .github/workflows/nodejs.yml
# 👆 Это путь к файлу — GitHub Actions ожидает workflows в .github/workflows

name: Node.js CI
# 🏷 Название workflow — будет отображаться в GitHub как "Node.js CI"

on:
  push:
    branches: [ main ]
    # 🟢 Запускать workflow при пуше в ветку main
  pull_request:
    branches: [ main ]
    # 🔵 Также запускать при pull request в main (например, при создании PR)

jobs:
  build:
    runs-on: ubuntu-latest
    # ☁️ Используем виртуальную машину GitHub на Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # 📥 Шаг 1: Клонируем репозиторий в рабочее пространство GitHub Runner

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          # 🔧 Шаг 2: Устанавливаем Node.js версии 18 (можно изменить на нужную)

      - name: Install dependencies
        run: npm install
        # 📦 Шаг 3: Устанавливаем зависимости из package.json

      - name: Lint code
        run: npm run lint
        # 🔍 Шаг 4 (по желанию): Проверяем код линтером (если есть npm script "lint")

      - name: Run unit tests
        run: npm run test
        # 🧪 Шаг 5: Запускаем unit-тесты (Jest по умолчанию в NestJS)

      # - name: Run e2e tests
      #   run: npm run test:e2e
      #   # 🔸 Этот шаг закомментирован, т.к. ты пока не используешь БД
      #   # 🔸 Когда подключишь базу — можно раскомментировать

# ✅ В итоге: на каждый push/PR в main — автоматическая сборка и тестирование!
